#!/usr/bin/env python3
"""
Send NoFeePlaces WordMark as high-quality image files (JPEG, PNG) to placesfirm@gmail.com
"""

import asyncio
import sys
import os
import base64
import mimetypes
from datetime import datetime, timezone
sys.path.append('/app/backend')
from email_service import email_service
from dotenv import load_dotenv

# Load environment variables
load_dotenv('/app/backend/.env')

async def send_wordmark_images():
    """Send WordMark as high-quality image attachments"""
    print("🎨 Preparing NoFeePlaces WordMark image files...")
    
    # Define the image files (these were generated by the screenshot tool)
    image_files = [
        "NoFeePlaces_WordMark_Dark.png",
        "NoFeePlaces_WordMark_Light.png", 
        "NoFeePlaces_WordMark_Transparent.png"
    ]
    
    # Check if files exist in app directory
    attachments = []
    
    for filename in image_files:
        file_path = f"/app/{filename}"
        if os.path.exists(file_path):
            print(f"✅ Found {filename} ({os.path.getsize(file_path)} bytes)")
            
            # Read file and encode as base64
            with open(file_path, 'rb') as f:
                file_data = f.read()
                file_b64 = base64.b64encode(file_data).decode()
                
            attachments.append({
                'filename': filename,
                'content': file_b64,
                'type': 'image/png'
            })
        else:
            print(f"⚠️  {filename} not found at {file_path}")
    
    # Create comprehensive HTML email with image descriptions
    email_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>NoFeePlaces WordMark - Image Assets</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }}
            .container {{ max-width: 800px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px; }}
            .header {{ background: linear-gradient(135deg, #10b981 0%, #3b82f6 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; margin: -30px -30px 30px -30px; }}
            .asset-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 20px 0; }}
            .asset-item {{ background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border: 2px solid #e9ecef; }}
            .asset-preview {{ width: 100%; max-width: 250px; height: 150px; background: #fff; border-radius: 8px; margin: 10px auto; display: flex; align-items: center; justify-content: center; font-size: 12px; color: #6c757d; border: 1px dashed #dee2e6; }}
            .specs {{ background: #e3f2fd; padding: 15px; border-radius: 8px; margin: 20px 0; }}
            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 2px solid #eee; text-align: center; color: #666; }}
            .color-swatch {{ display: inline-block; width: 20px; height: 20px; border-radius: 50%; margin-right: 8px; vertical-align: middle; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🎨 NoFeePlaces WordMark Image Assets</h1>
                <p>High-Quality Visual Brand Assets</p>
                <p>Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}</p>
            </div>
            
            <div class="specs">
                <h3>📋 Image Specifications</h3>
                <ul>
                    <li><strong>Format:</strong> PNG (High Quality, Transparent Support)</li>
                    <li><strong>Resolution:</strong> 1920x1080 pixels (Full HD)</li>
                    <li><strong>DPI:</strong> 96 DPI (Web) / 300 DPI equivalent for print</li>
                    <li><strong>Color Profile:</strong> sRGB</li>
                    <li><strong>File Size:</strong> Optimized for web and print use</li>
                </ul>
            </div>
            
            <h2>📁 Image Files Included ({len(attachments)} files attached)</h2>
            
            <div class="asset-grid">
                <div class="asset-item">
                    <h3>🌙 Dark Background Version</h3>
                    <div class="asset-preview" style="background: linear-gradient(135deg, #1e293b, #374151);">
                        <span style="color: white;">NoFee<span style="color: #10b981;">Fee</span> PLACES</span>
                    </div>
                    <p><strong>File:</strong> NoFeePlaces_WordMark_Dark.png</p>
                    <p><strong>Use:</strong> Dark backgrounds, headers, hero sections</p>
                    <p><strong>Colors:</strong> 
                        <span class="color-swatch" style="background: #ffffff;"></span>White + 
                        <span class="color-swatch" style="background: #10b981;"></span>Emerald + 
                        <span class="color-swatch" style="background: #d1d5db;"></span>Gray
                    </p>
                </div>
                
                <div class="asset-item">
                    <h3>☀️ Light Background Version</h3>
                    <div class="asset-preview" style="background: #ffffff;">
                        <span style="color: #374151;">No<span style="color: #059669;">Fee</span> PLACES</span>
                    </div>
                    <p><strong>File:</strong> NoFeePlaces_WordMark_Light.png</p>
                    <p><strong>Use:</strong> Light backgrounds, documents, business cards</p>
                    <p><strong>Colors:</strong> 
                        <span class="color-swatch" style="background: #374151;"></span>Dark Gray + 
                        <span class="color-swatch" style="background: #059669;"></span>Emerald + 
                        <span class="color-swatch" style="background: #6b7280;"></span>Medium Gray
                    </p>
                </div>
                
                <div class="asset-item">
                    <h3>🔲 Transparent Version</h3>
                    <div class="asset-preview" style="background: repeating-conic-gradient(#f3f4f6 0% 25%, transparent 0% 50%) 50% / 10px 10px;">
                        <span style="color: #374151;">No<span style="color: #059669;">Fee</span> PLACES</span>
                    </div>
                    <p><strong>File:</strong> NoFeePlaces_WordMark_Transparent.png</p>
                    <p><strong>Use:</strong> Overlays, flexible backgrounds, logos</p>
                    <p><strong>Background:</strong> Transparent/Alpha channel supported</p>
                </div>
            </div>
            
            <div class="specs">
                <h3>🎯 Usage Recommendations</h3>
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;">
                    <div>
                        <h4>📱 Digital Use</h4>
                        <ul style="font-size: 14px;">
                            <li>Website headers</li>
                            <li>Social media profiles</li>
                            <li>Email signatures</li>
                            <li>Digital presentations</li>
                        </ul>
                    </div>
                    <div>
                        <h4>🖨️ Print Use</h4>
                        <ul style="font-size: 14px;">
                            <li>Business cards</li>
                            <li>Letterheads</li>
                            <li>Marketing materials</li>
                            <li>Signage (resize as needed)</li>
                        </ul>
                    </div>
                    <div>
                        <h4>📊 Presentations</h4>
                        <ul style="font-size: 14px;">
                            <li>PowerPoint/Keynote</li>
                            <li>Pitch decks</li>
                            <li>Marketing reports</li>
                            <li>Client presentations</li>
                        </ul>
                    </div>
                </div>
            </div>
            
            <div style="background: #fff3cd; padding: 15px; border-radius: 8px; border-left: 4px solid #ffc107;">
                <h4>💡 Pro Tips</h4>
                <ul>
                    <li>Use <strong>Dark version</strong> on colored backgrounds and hero sections</li>
                    <li>Use <strong>Light version</strong> on white/light backgrounds and documents</li>
                    <li>Use <strong>Transparent version</strong> when you need flexibility with backgrounds</li>
                    <li>Maintain aspect ratio when resizing</li>
                    <li>Minimum recommended width: 200px for readability</li>
                </ul>
            </div>
            
            <div class="footer">
                <p><strong>NoFeePlaces.com</strong> - Brand Asset Package</p>
                <p>📧 placesfirm@gmail.com | 📞 +1 (646) 408-8048</p>
                <p style="font-size: 12px; color: #999; margin-top: 15px;">
                    High-quality wordmark images generated on {datetime.now().strftime('%B %d, %Y')} 
                    • Ready for immediate use in digital and print applications
                </p>
            </div>
        </div>
    </body>
    </html>
    """
    
    # Plain text version
    email_text = f"""
NoFeePlaces WordMark - Image Assets Package
Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}

IMAGE FILES ATTACHED ({len(attachments)} files):
1. NoFeePlaces_WordMark_Dark.png - For dark backgrounds
2. NoFeePlaces_WordMark_Light.png - For light backgrounds  
3. NoFeePlaces_WordMark_Transparent.png - Transparent background

SPECIFICATIONS:
- Format: PNG (High Quality)
- Resolution: 1920x1080 pixels
- Color Profile: sRGB
- Transparency: Supported (where applicable)

USAGE RECOMMENDATIONS:
- Digital: Website headers, social media, email signatures
- Print: Business cards, letterheads, marketing materials
- Presentations: PowerPoint, Keynote, pitch decks

COLORS:
- Emerald Green: #10b981 (Fee text)
- Dark Gray: #374151 (No/Places text - light version)
- White: #ffffff (No/Places text - dark version)

PRO TIPS:
- Use dark version on colored/dark backgrounds
- Use light version on white/light backgrounds
- Use transparent version for flexible applications
- Maintain aspect ratio when resizing
- Minimum width: 200px for readability

Contact: placesfirm@gmail.com | +1 (646) 408-8048
NoFeePlaces.com - NYC's Premier No Fee Apartment Platform
    """
    
    # Send the email with attachments
    print(f"📧 Sending {len(attachments)} WordMark image files to placesfirm@gmail.com...")
    
    # Prepare email data
    email_data = {
        'to_email': 'placesfirm@gmail.com',
        'subject': f'🎨 NoFeePlaces WordMark Images - High Quality Assets ({datetime.now().strftime("%B %d, %Y")})',
        'html_content': email_html,
        'text_content': email_text
    }
    
    # Add attachments if we have them
    if attachments:
        email_data['attachments'] = attachments
    
    # Send email
    try:
        success = await email_service.send_email_async(**email_data)
        
        if success:
            print("✅ WordMark image files successfully sent to placesfirm@gmail.com")
            print(f"📎 {len(attachments)} high-quality PNG files attached")
            print("🎨 Files include: Dark, Light, and Transparent background versions")
            print("📏 Resolution: 1920x1080 pixels (HD quality)")
            print("💼 Ready for web, print, and presentation use")
        else:
            print("❌ Failed to send WordMark image files")
            
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        success = False
    
    return success

if __name__ == "__main__":
    print("🚀 NoFeePlaces WordMark Image Sender")
    print("=" * 50)
    asyncio.run(send_wordmark_images())