-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLsN7d4TIajBf1oP1
n/Ae++THcivaEYTC5zCf43wBzYugCgYIKoZIzj0DAQehRANCAAQFPOVnsKtYDuVt
+jXBu8iTp7NRH5BZRoDwp610O/Y3dPd8oDWkQYOzDOS6PfXCKRT20mMpWkwpaMie
XHUhZRPR
-----END PRIVATE KEY-----